### ISSUE TITLE
MySQL fails with Error: Lost connection to MySQL server at 'sending authentication information', system error: 32

### ISSUE THREAD

**Issue by alex-kovshovik** [mezis/mrd#8]
This is a problem that I've been fighting for a while now, but finally solved for my main MySQL server instance on OSX. The fix was a simple configuration change in /etc/my.cnf:

``` bash
innodb_file_per_table = OFF
```

I described why this is occasionally happening on OSX machines here: http://stackoverflow.com/questions/17813630/mysql-5-6-headaches-on-mac-osx/22773887#22773887

mrd gem generates its own MySQL configuration file with innodb_file_per_table turned ON (hard-coded), which causes MySQL server to fail on my environment.

Since this gem is meant for OSX (looks like), I think it would be reasonable to **change innodb_file_per_table option to OFF** in mrd code. I think it is a better default, because OSX by default only allows 256 open file handles per process, so having each table in its own file is sub-optimal for reasonable size databases. I don't think this option has to be made configurable with the command line switch either, because there is no performance impact in having all data in 1 file on a RAM disk.

I already made a change on the forked version of mrd and it fixed the issue for everybody at my company who uses mrd: https://github.com/aspushkinus/mrd. I would've submitted a pull request, but this option change could be debatable.

Please let me know if pull request is OK for this change.

Thanks,
Alex.

**Comment by mezis** [comment]
> Please let me know if pull request is OK for this change.

Sorry Alex, I know it's been a while; but yes, in my opinion such a change is reasonable for a Ramdisk-based database.

(Note that for a "real" database I wouldn't recommend it, as `innodb_file_per_table` can be much more efficient than a single blob, and the 256 open file limit can easily be changed using sysctl).

**Comment by alex-kovshovik** [comment]
Thank you @mezis, the pull request is created: https://github.com/mezis/mrd/pull/10
